// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/types/supabase';

const SUPABASE_URL = "https://jgrfditkebphtpjgcogo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpncmZkaXRrZWJwaHRwamdjb2dvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3NzE3ODQsImV4cCI6MjA2MjM0Nzc4NH0.tQaigo8w4p-vh65MuFlbiPYqBn3O_pkBVRt2-AfEsJ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);